### ISSUE TITLE
Where are index.html?

### ISSUE THREAD

**Issue by invious** [att/XACML#27]
Attempting to run admin console using RunJettyRun, WEB-INF shows `NOT FOUND` when I navigate to the folder. Looking at web.xml I see a bunch of files, that I do not see in the project. Are these generated, or missing?

**Comment by ygrignon** [comment]
Look at ygrignon-sfdc/XACML for fixed pom.xml files addressing this issue among others.

**Comment by pdragosh** [comment]
Yes we need to finish building the pom.xml for the REST and PAP admin interfaces. Will try to do this asap.

**Comment by invious** [comment]
I swapped out the pom with https://github.com/ygrignon-sfdc/XACML/blob/master/XACML-PAP-ADMIN/pom.xml but I am still seeing NOT FOUND, even though directories are matched up as ones in pom file. Still following instructions in wiki to deploy with RunJetty, am I missing something else?

**Comment by pdragosh** [comment]
We have been using the Maven plugin to run Jetty, instead of the Eclipse Plugin. I just tried the latest Eclipse 9.0.0.M3 and it has bugs. The v8.1.8.v20121106 also seems to exhibit different problems with the persistence provider. But I'm not seeing the problem you are describing. 

I am going to commit the changes so that you could run from command line using Maven. Hopefully that would work for you: 'mvn jetty:run-war'

Then see if I can figure out how to get it to work under Eclipse Jetty Plugin.

**Comment by invious** [comment]
This was the install instructions I was using previously: https://github.com/att/XACML/wiki/XACML-PAP-ADMIN---Admin-Console-and-Policy-Editing-application

can you give updated instructions? Also clarify which pom is correct for the new instructions?
